name: Protect Main Branch
on:
  push:
    branches: [main]
jobs:
  protect:
    runs-on: ubuntu-latest
    steps:
      - name: Check pusher
        run: |
          # Admins 팀 멤버 목록 (실제 사용자 이름으로 대체)
          ADMINS=("admin-user1" "admin-user2")
          if [[ ! " ${ADMINS[*]} " =~ " ${{ github.actor }} " ]]; then
            echo "Direct push to main is not allowed for ${{ github.actor }}!"
            exit 1
          fi
